// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu03BANQg7OVd9MYULTlFgxaTX091w-tw',
    appId: '1:149185348244:web:36f1b98b29e0d573876a81',
    messagingSenderId: '149185348244',
    projectId: 'berita-49371',
    authDomain: 'berita-49371.firebaseapp.com',
    storageBucket: 'berita-49371.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG0lhukAaz1QkJ4jMxNWAQWiuUlDfT-U0',
    appId: '1:149185348244:android:59b6f9e03ebbaebb876a81',
    messagingSenderId: '149185348244',
    projectId: 'berita-49371',
    storageBucket: 'berita-49371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCS7Wb2prhym_iC-T3hLXIdl_jb3nkCg',
    appId: '1:149185348244:ios:f3d58e64722c3b35876a81',
    messagingSenderId: '149185348244',
    projectId: 'berita-49371',
    storageBucket: 'berita-49371.appspot.com',
    iosClientId: '149185348244-oglto43e2fuqr7pfitbgo9q9bj5objq2.apps.googleusercontent.com',
    iosBundleId: 'com.zeekands.banjarnegaranews.banjarnegaranews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCS7Wb2prhym_iC-T3hLXIdl_jb3nkCg',
    appId: '1:149185348244:ios:f3d58e64722c3b35876a81',
    messagingSenderId: '149185348244',
    projectId: 'berita-49371',
    storageBucket: 'berita-49371.appspot.com',
    iosClientId: '149185348244-oglto43e2fuqr7pfitbgo9q9bj5objq2.apps.googleusercontent.com',
    iosBundleId: 'com.zeekands.banjarnegaranews.banjarnegaranews',
  );
}
